I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1723, in script
    
ScriptError: could not find label 'nuit2_fin'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1723, in script
    
  File "F:\Utilitaires\renpy-7.3.5-sdk\renpy\ast.py", line 1697, in execute
    rv = renpy.game.script.lookup(target)
  File "F:\Utilitaires\renpy-7.3.5-sdk\renpy\script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'nuit2_fin'.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
EthiQuest 1.2
Fri Jun 05 19:52:01 2020
