I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 263, in script
    with dissolve
  File "game/script.rpy", line 263, in <module>
    with dissolve
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 263, in script
    with dissolve
  File "F:\Utilitaires\renpy-7.3.5-sdk\renpy\ast.py", line 2108, in execute
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "F:\Utilitaires\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 263, in <module>
    with dissolve
NameError: name 'false' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
EthiQuest 1.1
Fri May 22 15:46:27 2020
